### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by 007invictus** [wangxiang1230/OadTR#19]
in 45and47 line of the document "dataset.py" 
did you want to write self.data_root instead pickle_root?

**Comment by 007invictus** [comment]
and i met an error:
Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main(args)
  File "main.py", line 150, in main
    args.clip_max_norm)
  File "/data/wtyuan/git/OadTR/train.py", line 65, in train_one_epoch
    model(camera_inputs, motion_inputs)
  File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/wtyuan/git/OadTR/transformer_models/ViT.py", line 160, in forward
    x = self.linear_encoding(x)
  File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (8192x4096 and 3072x1024)

could you please give some advices?

**Comment by wangxiang1230** [comment]
> and i met an error: Traceback (most recent call last): File "main.py", line 197, in main(args) File "main.py", line 150, in main args.clip_max_norm) File "/data/wtyuan/git/OadTR/train.py", line 65, in train_one_epoch model(camera_inputs, motion_inputs) File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/data/wtyuan/git/OadTR/transformer_models/ViT.py", line 160, in forward x = self.linear_encoding(x) File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward return F.linear(input, self.weight, self.bias) File "/data/wtyuan/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear return torch._C._nn.linear(input, weight, bias) RuntimeError: mat1 and mat2 shapes cannot be multiplied (8192x4096 and 3072x1024)
> 
> could you please give some advices?

It looks like you are using the Thumos14-Kinetics feature, which is 4096-dim (rgb: 2048, flow: 2048). You need to change the network input dimension by "python main.py --dim_feature 4096“.
